# Generated by Django 5.2.2 on 2025-06-11 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_booking_date_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
