# Generated by Django 5.2.2 on 2025-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(choices=[('stem_building', 'Stem Building'), ('building_A', 'Building A'), ('building_B', 'Building B'), ('building_C', 'Building C'), ('building_D', 'Building D'), ('building_T', 'Building T')], default='stem_building', max_length=20),
        ),
    ]
