# Generated by Django 5.2.2 on 2025-06-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
