# Generated by Django 5.2.2 on 2025-06-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='completed',
        ),
    ]
